# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
            ],
        ),
    ]
