# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-24 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0002_auto_20190224_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcustomer',
            name='loan_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
