# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0003_auto_20190224_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcustomer',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='bankcustomer',
            name='loan_amount',
            field=models.FloatField(default=1, verbose_name=b'loan_amount'),
            preserve_default=False,
        ),
    ]
