# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0004_auto_20190224_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcustomer',
            name='loan_amount',
            field=models.FloatField(verbose_name='loan_amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='User', max_length=200),
        ),
    ]
